package it.prova.pokeronline.web.api.exception;

public class AlreadyInATavoloException extends RuntimeException{
	public AlreadyInATavoloException(String message) {
		super(message);
	}
}
